title: Progression Pack
baseurl: "" 
url: ""
framework_name: Design Careers
version: "0.1.2"

include: ['_pages']
exclude: ['bin', 'Makefile', 'README.md', 'Gemfile', 'Gemfile.lock']

collections:
  skills:
    output: true
    permalink: /:collection/:name
  team:
    output: true
  levels:
    output: true

sass:
  style: compressed